### ISSUE TITLE
can not compile on Linux

### ISSUE THREAD

**Issue by tissatussa** [Noxmor/Lunox#1]
hi, i tried but failed .. there's no makefile .. and what is `cbrew` ? I'm not a beginner at Linux / compiling .. can you help me out ?

[ i'm on Xubuntu 22.04 ]

**Comment by Noxmor** [comment]
[cbrew](https://github.com/Noxmor/cbrew) is a build tool for C projects I wrote in the past for fun and because I'm not the greatest fan of make. Since I wanted some practical use cases for cbrew, Lunox uses cbrew as a build tool. The build tool was designed with cross-platform support in mind, however as of right now cbrew is only implemented for Windows.

I may come back and add Linux support in the future, since I'm getting used to using Linux, thanks to my university.

If I remember correctly, Lunox internally does not use any platform specific code, so a quick script to compile all *.c files should do the trick.

**Comment by tissatussa** [comment]
thanks for this explanation.
if you're familiar with Linux, you don't want to use another OS.. Linux feels good, can be fully configured, has all the type of tools you'll ever need and it's open and free. Regarding programming, you should focus on Linux when writing code and finally alter some to make it work on Windows also -- but hee, i'm a Linux evangelist :-)

**Comment by Noxmor** [comment]
I'm definitely not a Linux evangelist, but the more I work on Linux the more I enjoy it. Maybe I will abandon Windows one day in the future, who knows. Speaking of Linux: cbrew now works on Linux! Compiling Lunox should no longer be an issue :)

**Comment by tissatussa** [comment]
> cbrew now works on Linux!

i read the info at https://github.com/Noxmor/cbrew but it's not clear to me how to compile .. i see the `cbrew.h` file (the only code file of that link) is same as the one for Lunox .. i must create a `target directory` and an `object directory`, but where in the folder tree ? And then which command to enter for compiling and where in the folder tree ? I'm familiar with g++ and gcc but please give an example.

**Comment by Noxmor** [comment]
`cbrew` is the build system you will have to locally bootstrap **once**. While having a terminal opened in the directory where the `cbrew` directory is located compile cbrew for example like this: `gcc cbrew/cbrew.c -o cbrew/cbrew`
Now you can just call `cbrew/cbrew` to automatically build everything. Now, whenever a change happens (most likely due to a commit of mine) to the build specification (cbrew/cbrew.c) cbrew will automatically recompile itself before building the project again.

**Comment by tissatussa** [comment]
> ..Now you can just call cbrew/cbrew to automatically build everything..

that worked !
now i have 3 versions : -Debug -Release and -Dist but none of them give the expected output after the command `uci` .. is Lunox really an UCI engine ? I want it to compete in CuteChess ..

**Comment by Noxmor** [comment]
I stopped working actively on Lunox as I was about to implement the uci interface. My local repo contains most of the relevant code, however is currently in a state where it does not even compile, thus I never comitted it, and currently I do not have the time to get really back into it and continue working, sorry.
